# Site settings
title: qin4zhang Blog
SEOTitle: 西十四的猫 | qin4zhang Blog
header-img: img/post-bg-desk.jpg
email: hbzhangzhen2010@163.com
description: "Luck is what happens when preparation meets opportunity."
keyword: "西十四的猫, qin4zhang Blog, qin4zhang"
url: "https://qin4zhang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qin4zhang/qin4zhang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The best way to predict the future is to create it."
sidebar-avatar: /img/about-cat.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     qin4zhang
github_username:    qin4zhang
linkedin_username:  zhen-zhang-258b16a4


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#  repo: qiubaiying.github.io    #仓库名称
#  owner: qiubaiying    #github用户名
#  admin: qiubaiying
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-141697403-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "spring.io",
        href: "https://spring.io/"
    },
    {
        title: "Readhub",
        href: "https://readhub.cn/topics"
    },
    {
        title: "阮一峰的网络日志",
        href: "http://www.ruanyifeng.com/blog/"
    }
]
